### ISSUE TITLE
rails g jekyll:blog failing

### ISSUE THREAD

**Issue by natanio** [zbruhnke/bloggy#22]
Trying to look for a simple way to add a blog, and this option looked very promising. Rails 4.2.5 app is new, running Ruby 2.2.3, but getting the below error when I run 'rails g jekyll:blog':

/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'bloggy'. (Bundler::GemRequireError)

Thanks for any help.

**Comment by Deuteu** [comment]
+1

**Comment by oreeve** [comment]
:+1: for ruby 2.2.1 also

**Comment by cantwelt** [comment]
Any solution yet. Same error here.

**Comment by cpsteine** [comment]
Yes, not working with 2.2.2—but I have used it until now. May have to go homebrew CMS.

**Comment by DonnaLou** [comment]
rails g jekyll:blog
/home/loudon/.rvm/gems/ruby-2.2.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:89:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'bloggy'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant Syck

:(

**Comment by zbruhnke** [comment]
wow sorry everyone - havent checked this in a while and honestly had no idea people were still using the gem - I can take a look at it today if its helpful
